{
 "title": "NR7101 Status",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Current Band",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM \"autogen\".\"status\" ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RSRP",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "alias": "5G",
     "measurement": "status",
     "select": [
      [
       { "params": [ "NSA_RSRP" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "4G",
     "measurement": "status",
     "select": [
      [
       { "params": [ "INTF_RSRP" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RSRQ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "5G",
     "measurement": "status",
     "select": [
      [
       { "params": [ "NSA_RSRQ" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "4G",
     "measurement": "status",
     "select": [
      [
       { "params": [ "INTF_RSRQ" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SINR",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "alias": "5G",
     "measurement": "status",
     "select": [
      [
       { "params": [ "NSA_SINR" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "4G",
     "measurement": "status",
     "select": [
      [
       { "params": [ "INTF_SINR" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RSRP",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "dBm" }
   ],
   "targets": [
    {
     "alias": "5G",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "query": "SELECT mean(\"NSA_RSRP\") FROM \"autogen\".\"status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "NSA_RSRP" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "4G",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "select": [
      [
       { "params": [ "INTF_RSRP" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RSRP",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "dBm" }
   ],
   "targets": [
    {
     "alias": "5G",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "query": "SELECT mean(\"NSA_RSRP\") FROM \"autogen\".\"status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "NSA_RSRP" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "4G",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "select": [
      [
       { "params": [ "INTF_RSRP" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SINR",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "5G",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "query": "SELECT mean(\"NSA_RSRP\") FROM \"autogen\".\"status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "NSA_SINR" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "4G",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "select": [
      [
       { "params": [ "INTF_SINR" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "dB" }
   ],
   "targets": [
    {
     "alias": "4G",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "query": "SELECT mean(\"NSA_RSRP\") FROM \"autogen\".\"status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "INTF_RSSI" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "ping",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "status",
     "query": "SELECT mean(\"NSA_RSRP\") FROM \"autogen\".\"status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ping_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Received",
     "measurement": "status",
     "query": "SELECT mean(\"NSA_RSRP\") FROM \"autogen\".\"status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "BytesReceived" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "Sent",
     "measurement": "status",
     "query": "SELECT mean(\"NSA_RSRP\") FROM \"autogen\".\"status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "BytesSent" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "Received errors",
     "measurement": "status",
     "query": "SELECT mean(\"NSA_RSRP\") FROM \"autogen\".\"status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ErrorsReceived" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "Sent errors",
     "measurement": "status",
     "query": "SELECT mean(\"NSA_RSRP\") FROM \"autogen\".\"status\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ErrorsSent" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  }
 ]
}